### ISSUE TITLE
Fit tracks not being recognized

### ISSUE THREAD

**Issue by MariaCervera** [JamesRunnalls/photomapa#5]
Only gpx files seems to be recognised properly. Would it be possible to accept also .fit files?
Thanks!

**Comment by JamesRunnalls** [comment]
Could you provide an example file?

**Comment by JamesRunnalls** [comment]
It is possible to convert files manually using "Route Converter | AllTrails" https://www.alltrails.com/converter

**Comment by JamesRunnalls** [comment]
1f504b73d50e1471d086df0a72cbc7ed33da276e
